# 工作流的名称
name: Lejian Sports Runner

# 触发工作流的事件
on:
  # 1. 允许你手动在Actions页面点击按钮来运行，方便测试
  workflow_dispatch:
  
  # 2. 定时运行
schedule:
    # cron表达式，对应北京时间 晚上 21:21
    - cron: '21 13 * * *'
# 定义要执行的任务
jobs:
  run-script:
    # 使用最新的Ubuntu Linux环境来运行
    runs-on: ubuntu-latest

    # 任务的步骤
    steps:
      # 第一步：把你的代码下载到运行环境中
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 第二步：设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 你可以指定需要的Python版本

      # 第三步：安装脚本依赖的库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 第四步：运行你的Python脚本
      - name: Run the Python script
        env:
          # 将我们设置的Secrets注入到环境变量中
          LEJIAN_USERNAME: ${{ secrets.LEJIAN_USERNAME }}
          LEJIAN_PASSWORD: ${{ secrets.LEJIAN_PASSWORD }}
        run: |
          # 注意：这里的文件名要和你上传的Python脚本名一致
          python run.py
