name: Lejian Sports Runner

on:
  # 允许你手动从 Actions 页面运行，方便随时使用
  workflow_dispatch:

  # 每天的正式定时任务
  schedule:
    # cron 表达式使用 UTC 时间，已为你换算成北京时间
    - cron: '0 23 * * *'   # 对应北京时间 早上 7:00
    - cron: '20 23 * * *'  # 对应北京时间 早上 7:20
    - cron: '40 23 * * *'  # 对应北京时间 早上 7:40

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：下载你的代码到运行环境中
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 步骤2：设置好 Python 3.10 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 步骤3：安装 requirements.txt 中定义的依赖库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 步骤4：运行你的 Python 脚本
      - name: Run the Python script
        env:
          # 从仓库的 Secrets 中读取账号密码并设置为环境变量
          LEJIAN_USERNAME: ${{ secrets.LEJIAN_USERNAME }}
          LEJIAN_PASSWORD: ${{ secrets.LEJIAN_PASSWORD }}
        # 运行 run.py 文件 (如果你的文件名不是run.py，请修改这里)
        run: python run.py
