name: Run Python Script

on:
  schedule:
    - cron: '0 23 * * *'  # 对应北京时间早上 7:00
    - cron: '20 23 * * *' # 对应北京时间早上 7:20
    - cron: '40 23 * * *' # 对应北京时间早上 7:40
    - cron: '49 15 * * *' # 对应北京时间早上 7:40

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # 你可以指定需要的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python run.py # 将 your_script.py 替换为你的脚本文件名
